### PR TITLE
Additional reverse geocoder function

### PR DESCRIPTION
**Pull request by BikersDelight**
Added an additional function to reverse geocode with an optional locale.

### CODE REVIEW

**Comment by mxcl** [comment]
Thanks, our other `reverseGeocodeLocation` function is named: `reverseGeocode(location:)` and while I now think this was the wrong decision I think we should be internally consistent.

**Comment by BikersDelight** [comment]
I used the same implementation as Apple did with CoreLocation, so consistency-wise I’d suggest to use their implementation as well for the other function. Although this introduces a breaking change.

**Comment by mxcl** [comment]
> Although this introduces a breaking change.

Yes, we can do this for PMK7, which is in production, I'll make a note to do so. However we should remain internally consistent with PMK6 for this PR.

**Comment by BikersDelight** [comment]
I fully agree and will update the PR accordingly.

**Comment by mxcl** [comment]
Many thanks.

**Comment by BikersDelight** [comment]
No worries! Done with pleasure...

**Pull request merged**
