### PR TITLE
Fix issue when trying to promote from whenInUse to always permissions

### PR DESCRIPTION
**Pull request by paweljankowski**

### CODE REVIEW

**Comment by mxcl** [comment]
You marvelous person you.

**Comment by paweljankowski** [comment]
@mxcl  Please hold on with merging this. I've found one case that fix doesn't work...

**Comment by mxcl** [comment]
np, waiting on the CI anyway. Also I'll try to do a thorough review.

**Comment by mxcl** [comment]
Please let me know if the fix works.

**Comment by bruno-rocha-movile** [comment]
Did this end up never being shipped? Looking forward for it, as currently the promotion request's location manager is getting deallocated prematurely and the window dismisses before the user can act 😢

@paweljankowski What is the case that's still broken? Would love to help as I am in a big need of this fix 😞

**Comment by mxcl** [comment]
If you have a bug report please open a new ticket because as you can see if you click the commit that closed this ticket, we consider this issue fixed and if you click through from the commit you can see that we released a new version of PromiseKit with the fix.

**Comment by paweljankowski** [comment]
Nope, the fix doesn't work for me :-(

**Comment by bruno-rocha-movile** [comment]
I saw the commit, I assumed it wasn't shipped because the contents of the commit were not in my `CLLocationManager+Promise.swift`. But it turns out it was, just written in a different way... Sorry for necro'ing the thread.

**Comment by mxcl** [comment]
K well, seemingly I didn't understand the bug properly. I don't have an app that promotes from whenInUse to always so one of you guys maybe can provide the fix? I'll open a ticket for the bug.

**Comment by ricsantos** [comment]
Just came across this issue myself with PromiseKit 6.2.5. Should #4 be reopened, or want me to raise a new bug?

Usage: first call with `.whenInUse` authorization suceeds, then any further calls to `CLLocationManager.requestAuthorization(type:)` fail to return.

**Pull request closed without merging**
